### ISSUE TITLE
Broken download

### ISSUE THREAD

**Issue by Ikabodo** [rachsg7/ai-actors#1]
![image](https://github.com/rachsg7/ai-actors/assets/7766890/1d2e40b4-f4a2-4834-8ddd-43fd34223c9d)

I think something went wrong with the upload of these two modules. :D

**Comment by docphil30** [comment]
Even using a new open-ai key, I can't generate an NPC in Foundry. I should point out that I tested under Forge and locally, in english and in French, with no change. The prompt translated into French works very well under chat-gpt out of module. The results are really good.

**Comment by rachsg7** [comment]
Resolved with 1.0.7
