### ISSUE TITLE
Folder dropdown doesn't populate

### ISSUE THREAD

**Issue by ohmusama** [rachsg7/ai-actors#3]
When saving an npc the drop down list with folders isn't populating with my existing actor folders.

![image](https://github.com/rachsg7/ai-actors/assets/220289/21c0692e-f0cd-4c23-b352-dc35f3596556)

**Comment by ohmusama** [comment]
a folder

![image](https://github.com/rachsg7/ai-actors/assets/220289/9758cc24-5aa6-442c-a0f8-af9304ca22cd)

**Comment by rachsg7** [comment]
Fixed as of 1.0.8
