### ISSUE TITLE
Is this compatible with the latest version of Foundry?

### ISSUE THREAD

**Issue by iwrz** [rachsg7/ai-actors#5]
It seems like there's a compatibility issue with the latest DND5e and midi qol modules.

**Comment by iwrz** [comment]
When using !gpt it returns ChatMessageMidi validation errors : type"0" is not a valid type for ChatMessage Document class [Detected 2 packages: system:dnd5e(3.3.1), midi-qol(11.6.9)].

Seems like a problem with dnd5e game system and midi-qol module.

![chatmidi validation](https://github.com/user-attachments/assets/a940579a-b71b-4d90-a2a9-4e29dbc6b7a9)

**Comment by rachsg7** [comment]
Thank you for finding this! Got it updated with compatibility for V12
